services:
  # main app 
  app:
    restart: always
    image: mcr.microsoft.com/devcontainers/python:1-3.8
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspaces
  
  # api backend image
  api:
    build: ../preqin-technical-test
    ports:
      - "8000:8000"

  
  